image: docker:latest
services:
  - docker:dind
stages:
  - deploy
step-deploy-production:
  stage: deploy
  before_script:
    - pwd
    - sudo chmod -R 777 .
    - sudo chmod -R 777 /var/www/surctf
    - sudo docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
    - sudo docker-compose down
    - sudo docker-compose push
    - sudo cp -R ./ /var/www/surctf
    - cd /var/www/surctf
  script:
    - sudo docker-compose -f docker-compose.yml build --no-cache
    - sudo docker-compose -f docker-compose.yml up -d

